
variables:
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
    - build

build & test:
    stage: build
    image: maven:3.6.2-jdk-11-slim
    artifacts:
        name: "$CI_COMMIT_REF_NAME"
        expire_in: 1 week
        paths:
            - 'target/singlepage-springboot-*.jar'
    cache:
        key: maven-repository
        paths:
            - .m2/repository
    script:
        - 'mvn $MAVEN_CLI_OPTS clean package -P all-tests'
